# Generated by Django 3.1.5 on 2021-01-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('languages', models.CharField(max_length=254)),
                ('site_line', models.URLField(max_length=254)),
                ('github_link', models.URLField(max_length=254)),
                ('image', models.ImageField(default='default_image.jpg', upload_to='')),
            ],
        ),
    ]
