# Generated by Django 3.1.5 on 2021-01-22 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='site_line',
            new_name='site_link',
        ),
    ]
